### ISSUE TITLE
Cant export result

### ISSUE THREAD

**Issue by VanessaEvo** [waived/mass-host-scanner#1]
First, thank u for the tool...
I have a problem when I want to export the results to TXT. The scan has been completed but I cannot export the scan results...

This is a screenshot of the tool...

![Abyss 1](https://github.com/user-attachments/assets/dbed7e9a-2ee7-47bd-9388-2d7d717f666e)
![Abyss 2](https://github.com/user-attachments/assets/a96fd8e9-755a-46ae-b0c5-31f933ea2005)

Thank you...

**Comment by waived** [comment]
As you can see by the error message, Abyss wont let you save any results until after the scan has complete. This was done in effort to avoid redundancy. After your scan is finished, are you still getting this error? I'm away on business till the 18th. I'll review the code, and if I find an issue, expect a fix sometime that evening; eastern timezone. Depending on how my schedule goes, it's also possible I'll post a fix sooner.

**Comment by waived** [comment]
When cleaning up my code and restructuring some of the layout, I must have accidentally deleted a line that was supposed to switch off the flag that tells Abyss there is an active scan going. Anyway, its fixed. Give it a try and let me know how it works!
